name: Java

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: [8, 11, 17]
        #include:
        #- os: macos-latest
        #  node-version: 18.x
        #- os: macos-14
        #  node-version: 18.x
          
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'zulu'
        cache: maven
    - uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.8.1
    - name: Maven Info
      run:  echo "home=$(mvn -v -q | grep "Maven home:" | sed -e 's/Maven home://' -e 's/^[[:space:]]*//')" >> $GITHUB_OUTPUT
      shell: bash
      id: maven
    - run: mvn --batch-mode install
      env:
        M2_HOME: '${{ steps.maven.outputs.home }}'
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test Results
        path: ${{ github.workspace }}/core/target/surefire-reports/TEST*.xml,${{ github.workspace }}/e2e-tests/target/surefire-reports/TEST*.xml
        reporter: java-junit

