name: Java

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: [8, 11, 17]
        #include:
        #- os: macos-latest
        #  node-version: 18.x
        #- os: macos-14
        #  node-version: 18.x
          
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'zulu'
        cache: maven
    - run: mvn --batch-mode install
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test Results
        path: ${{ github.workspace }}/core/target/surefire-reports/TEST*.xml,${{ github.workspace }}/e2e-tests/target/surefire-reports/TEST*.xml
        reporter: java-junit

